/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NowIndexRouteImport } from './routes/now/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as NowArchiveRouteImport } from './routes/now/archive'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NowIndexRoute = NowIndexRouteImport.update({
  id: '/now/',
  path: '/now/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const NowArchiveRoute = NowArchiveRouteImport.update({
  id: '/now/archive',
  path: '/now/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/now/archive': typeof NowArchiveRoute
  '/blog/': typeof BlogIndexRoute
  '/now/': typeof NowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/now/archive': typeof NowArchiveRoute
  '/blog': typeof BlogIndexRoute
  '/now': typeof NowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/now/archive': typeof NowArchiveRoute
  '/blog/': typeof BlogIndexRoute
  '/now/': typeof NowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/uses'
    | '/blog/$slug'
    | '/now/archive'
    | '/blog/'
    | '/now/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/uses'
    | '/blog/$slug'
    | '/now/archive'
    | '/blog'
    | '/now'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/uses'
    | '/blog/$slug'
    | '/now/archive'
    | '/blog/'
    | '/now/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UsesRoute: typeof UsesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  NowArchiveRoute: typeof NowArchiveRoute
  BlogIndexRoute: typeof BlogIndexRoute
  NowIndexRoute: typeof NowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now/': {
      id: '/now/'
      path: '/now'
      fullPath: '/now/'
      preLoaderRoute: typeof NowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now/archive': {
      id: '/now/archive'
      path: '/now/archive'
      fullPath: '/now/archive'
      preLoaderRoute: typeof NowArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UsesRoute: UsesRoute,
  BlogSlugRoute: BlogSlugRoute,
  NowArchiveRoute: NowArchiveRoute,
  BlogIndexRoute: BlogIndexRoute,
  NowIndexRoute: NowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
